// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'd05f4e58-b80d-4ebd-a6d7-c9cac216cd39',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'South Central US';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xDeploymentTestGroup2747' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-request-id': 'e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'x-ms-correlation-request-id': 'e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231925Z:e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:24 GMT',
  connection: 'close',
  'content-length': '116' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xDeploymentTestGroup2747' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-request-id': 'e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'x-ms-correlation-request-id': 'e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231925Z:e0e9310e-4a67-41b9-9969-90a30818c6f4',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:24 GMT',
  connection: 'close',
  'content-length': '116' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourceGroups/xDeploymentTestGroup2747\",\"name\":\"xDeploymentTestGroup2747\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '219',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': 'da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'x-ms-correlation-request-id': 'da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231926Z:da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourceGroups/xDeploymentTestGroup2747\",\"name\":\"xDeploymentTestGroup2747\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '219',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': 'da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'x-ms-correlation-request-id': 'da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231926Z:da796fb4-1dbb-46f8-a556-b380fdf7ddca',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': '23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'x-ms-correlation-request-id': '23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231927Z:23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:27 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2747?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': '23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'x-ms-correlation-request-id': '23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231927Z:23fe105a-4f16-4c9c-b2ee-b50a30bf1227',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:27 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '14988',
  'x-ms-request-id': 'ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'x-ms-correlation-request-id': 'ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231958Z:ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '14988',
  'x-ms-request-id': 'ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'x-ms-correlation-request-id': 'ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231958Z:ec1f6e2c-b0b8-47e9-8b7d-896ce47a34ff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '14994',
  'x-ms-request-id': '6e4476c2-72af-47d3-8233-9de00327e43d',
  'x-ms-correlation-request-id': '6e4476c2-72af-47d3-8233-9de00327e43d',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T232029Z:6e4476c2-72af-47d3-8233-9de00327e43d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:20:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI3NDctU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '14994',
  'x-ms-request-id': '6e4476c2-72af-47d3-8233-9de00327e43d',
  'x-ms-correlation-request-id': '6e4476c2-72af-47d3-8233-9de00327e43d',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T232029Z:6e4476c2-72af-47d3-8233-9de00327e43d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:20:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['xDeploymentTestGroup2747','Deploy11772'];};