// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'd05f4e58-b80d-4ebd-a6d7-c9cac216cd39',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'South Central US';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xDeploymentTestGroup2591' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14991',
  'x-ms-request-id': 'b66db30d-51bc-471b-baaf-f657f140612f',
  'x-ms-correlation-request-id': 'b66db30d-51bc-471b-baaf-f657f140612f',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231852Z:b66db30d-51bc-471b-baaf-f657f140612f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:51 GMT',
  connection: 'close',
  'content-length': '116' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xDeploymentTestGroup2591' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14991',
  'x-ms-request-id': 'b66db30d-51bc-471b-baaf-f657f140612f',
  'x-ms-correlation-request-id': 'b66db30d-51bc-471b-baaf-f657f140612f',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231852Z:b66db30d-51bc-471b-baaf-f657f140612f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:51 GMT',
  connection: 'close',
  'content-length': '116' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourceGroups/xDeploymentTestGroup2591\",\"name\":\"xDeploymentTestGroup2591\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '219',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': 'b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'x-ms-correlation-request-id': 'b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231853Z:b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourceGroups/xDeploymentTestGroup2591\",\"name\":\"xDeploymentTestGroup2591\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '219',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': 'b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'x-ms-correlation-request-id': 'b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231853Z:b76bb1b2-25e5-44ea-8b46-b716323400a1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI1OTEtU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-request-id': '4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'x-ms-correlation-request-id': '4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231854Z:4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:54 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/resourcegroups/xDeploymentTestGroup2591?api-version=2016-02-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI1OTEtU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-request-id': '4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'x-ms-correlation-request-id': '4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231854Z:4f46114b-7c2c-4000-a470-e28b77cf9f0c',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:18:54 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI1OTEtU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '14990',
  'x-ms-request-id': '9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'x-ms-correlation-request-id': '9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231925Z:9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:24 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/d05f4e58-b80d-4ebd-a6d7-c9cac216cd39/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YREVQTE9ZTUVOVFRFU1RHUk9VUDI1OTEtU09VVEhDRU5UUkFMVVMiLCJqb2JMb2NhdGlvbiI6InNvdXRoY2VudHJhbHVzIn0?api-version=2016-02-01')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '14990',
  'x-ms-request-id': '9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'x-ms-correlation-request-id': '9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'x-ms-routing-request-id': 'CENTRALUS:20161005T231925Z:9957e5aa-839a-4ef3-8da5-239ec9ba1918',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Wed, 05 Oct 2016 23:19:24 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['xDeploymentTestGroup2591','Deploy12836'];};